### ISSUE TITLE
Update commons-fileupload version due to multiple CVEs

### ISSUE THREAD

**Issue by manderson23** [graphql-java/graphql-java-servlet#76]
Multiple CVEs are published against commons-fileupload 1.3.1.

- https://nvd.nist.gov/vuln/detail/CVE-2016-1000031
- https://nvd.nist.gov/vuln/detail/CVE-2016-3092

These have both been resolved in commons-fileupload 1.3.3

**Comment by nrouge** [comment]
I just made a pull request that removes this library, not really necessary since Servlet 3.0.

**Comment by cgarrit-os** [comment]
@nrouge 

The pull request that removes commons-fileupload results in issues for those of us using spring-boot-starter.

The issue first manifests as an initialization error since org.apache.commons.io is no longer being pulled into the project via the graphql-java-servlet package.  Once this is resolved, we receive the following when posting via the graphiql interface.

java.lang.IllegalStateException: Unable to process parts as no multi-part configuration has been provided.

GET requests still work.  Please advise.

**Comment by marceloverdijk** [comment]
Thx @oliemansm for the investigation. For now probably the best option is to depend on `graphql-java-servlet` v`5.0.1`.
